version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # USER_CODE_PATH: /home/src/${PROJECT_NAME}
      USER_CODE_PATH: /Users/blessedmadukoma/Desktop/Code/learn/data-engineering/zoomcamp2022/week_2/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 6789:6789
    volumes:
      # - .:/home/src/
      # - ~/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
      # - .:/Users/blessedmadukoma/Desktop/Code/learn/data-engineering/zoomcamp2022/week_2
      - /Users/blessedmadukoma/Desktop/Code/learn/data-engineering/zoomcamp2022/week_2:/home/src
      - ~/Documents/secrets/personal-gcp.json:/Users/blessedmadukoma/Desktop/Code/learn/data-engineering/zoomcamp2022/week_1/terraform_gcp/terraform/de-zoomcamp-410913-ff0c577f1526.json
    restart: on-failure:5
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    container_name: ${PROJECT_NAME}-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
